language: node_js
node_js:
  - 7
  - 6
install:
  - sudo npm install -g typescript
  - sudo npm install -g mocha
  - npm install
  - sudo npm link
  - tsc --version
script:
  - npm run build
  - tscover --help
  - cat build/project.js
  # - npm test
